=head1 NAME

samu.pl -- Support Automatisation Management Utility

=head1 DESCRIPTION

This script is used as a wrapper script for automatisation task used by support.
To get information about any sub module call any option with help. Documentation and information can be reached under the respective sub module help.

=head1 SYNOPSIS

samu.pl [options] [function]

=head1 OPTIONS

=over

=item --help|-h

Print the help page

=item --man|-m

Print the man page with information about all modules

=item -v|-vv|-vvv|-vvvv

Increase verbosity of printing

=item -q|-qq|-qqq|-qqqq|-qqqqq|-qqqqqq

Decrease verbosity of printing

=back

=head1 FUNCTIONS

=over

=item vm

Access VM Entity functions

=item datastore

Access Datastore functions

=item ticket

Access ticket functions

=item kayako

Access kayako functions

=item bugzilla

Access bugzilla functions

=item admin

Higher level commands for administering or maintenance of the VCenter and environment

=item network

Network related functions

=back
