=head1 VM

=head3 SYNOPSIS

samu.pl vm [options] [function]

=head3 OPTIONS

=over

=item --help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item clone

Sub used to provision virtual machine guests from templates.

=item add

Sub to add different hardware to a guest

=item list

Sub to list different hardware of a guest

=item delete

Sub to delete/remove different hardware of a guest

=item change

Sub to change settings of a guest

=item info

Sub used to dump information about a virtual machine

=item convert_full

Converts a linked clone to a full clone

=item run

Run a command in a guest that has vmware tools

=item customization_status

Prints the customization status

=item transfer

Transfers file from or to a guest

=back

=head1 VM_functions

=head2 VM_clone_function

=head3 SYNOPSIS

samu.pl vm clone [options]

=head3 OPTIONS

=over

=item ticket

The ticket attached to the environment

=item os_temp

Which template to use

=item parent_pool

The machine should not be created at standard pool

=item memory

The machine should have different amount of memory than template

=item cpu

The machine cpu count should be different than template

=item domain

By default machine is created in workgroup, this option changes it to be added to support domain (only win)

=back

=head2 VM_convert_full_function

=head3 SYNOPSIS

samu.pl vm convert_full [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=back

=head2 VM_info_function

=head3 SYNOPSIS

samu.pl vm info [options] [function]

=head3 OPTIONS

=over

=back

=head3 FUNCTIONS

=over

=item dumper

This information is used for development purposes, It dumps all object information about virtual machine to STDOUT

=item runtime

Information about runtime environment

=back

=head2 VM_info_dumper_function

=head3 SYNOPSIS

samu.pl vm info dumper [options]

=head3 OPTIONS

=over

=item vmname

Which machines information should we dump (dumps raw hash)

=back

=head2 VM_info_runtime_function

=head3 SYNOPSIS

samu.pl vm info runtime [options]

=head3 OPTIONS

=over

=item vmname

Which machines runtime information should we dump (dumps raw hash)

=back

=head2 VM_transfer_function

=head3 SYNOPSIS

samu.pl vm transfer [options]

=head3 OPTIONS

=over

=item type

Direction of transfer: to/from

=item vmname

Name of virtual machine

=item guestusername

Username to use for log on

=item guestpassword

Password to use to log on

=item source

Source of file

=item dest

Destination of file

=item overwrite

Should files be overwritten

=back

=head2 VM_run_function

=head3 SYNOPSIS

samu.pl vm run [options]

=head3 OPTIONS

=over

=item vmname

Which machines runtime information should we dump (dumps raw hash)

=item guestusername

Guestname to authenticate with

=item guestpassword

Password to authenticate with

=item prog

Program to run. Full path should be given

=item prog_arg

Arguments to program

=item workdir

Working directory

=item env

Enviromental variables passed to program

=back

=head2 VM_customization_status_function

=head3 SYNOPSIS

samu.pl vm customization_status [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item wait

Should we wait for Fail or Finished status

=back
