=head1 BUGZILLA

=head3 SYNOPSIS

samu.pl bugzilla [options] [functions]

=head3 OPTIONS

=over

=item -help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item info

Gather information about bugzilla ticket

=back

=head1 BUGZILLA_functions

=head2 BUGZILLA_info_function

=head3 SYNOPSIS

samu.pl bugzilla [options]

=head3 OPTIONS

=over

=item ticket

The ticket number to gather information about

=back
