=head1 ADMIN

=head3 SYNOPSIS

samu.pl admin [functions] [options]

=head3 OPTIONS

=over

=item --help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item cleanup

Start the cleanup task to remove empty entities on the VCenter

=item test

Test connection to VCenter. Prints the Server time

=item pod2wiki

Transfer a pod file to Dokuwiki format

=item list

List information about environment

=back

=head1 ADMIN_functions

=head2 ADMIN_cleanup_function

=head3 SYNOPSIS

samu.pl admin cleanup [options]

=head3 OPTIONS

=over

=back

=head2 ADMIN_test_function

=head3 SYNOPSIS

samu.pl admin test [options]

=head3 OPTIONS

=over

=back

=head2 ADMIN_pod2wiki_function

=head3 SYNOPSIS

samu.pl admin pod2wiki [options]

=head3 OPTIONS

=over

=item in

The POD file to transfer

=item out

The output file

=item page

Pagename to upload to with namespace example a/b/c
a/b is namespace
c is pagename

=item dokuuser

The username to log into dokuwiki

=item dokuserver

The Dokuwiki server to use to log into. Defaults to Support server

=item dokupass

The password to use to log into dokuwiki

=back

=head2 ADMIN_list_function

=head3 SYNOPSIS

samu.pl admin list [options] [functions]

=head3 OPTIONS

=over

=back

=head3 FUNCTIONS

=over

=item folder

List information about requested folders

=item resourcepool

list information about requested resourcepools

=item linked_clones

list all linked clones to a template

=item vms

list requested vms on vcenter

=back

=head2 ADMIN_list_folder_function

=head3 SYNOPSIS

samu.pl admin list folder [options]

=head3 OPTIONS

=over

=item all

List content of all folders

=item name

List content of one folder

=item output

Type of output

=item noheader

Header row should be printed

=back

=head2 ADMIN_list_resourcepool_function

=head3 SYNOPSIS

samu.pl admin list resourcepool [options]

=head3 OPTIONS

=over

=item user

List resourcepool information of user

=item all

List all resourcepool information

=item name

List information of only one requested resourcepool

=item output

Type of output

=item noheader

Header information should be printed

=back

=head2 ADMIN_list_linked_clones_function

=head3 SYNOPSIS

samu.pl admin list linked_clones [options]

=head3 OPTIONS

=over

=item template

Name of template to list linked clones of

=back

=head2 ADMIN_list_vms_function

=head3 SYNOPSIS

samu.pl admin list vms [options]

=head3 OPTIONS

=over

=item name

List specific user vms (default to username option)

=item vm

List specific vm attributes

=item all

List all vms on vcenter

=item output

Type of output

=item noheader

Header information should be printed

=back
