=head1 NETWORK

Network related functions

=head3 SYNOPSIS

samu.pl network [options] [functions]

=head3 OPTIONS

=over

=item -help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item add

Add a distributed virtual switch to VCenter

=item create

Create a network interface with virtual machines

=item list_switch

List switches on VCenter

=item list_dvp

List distributed virtual portgroups on VCenter

=item delete

Remove distributed virtual switch from VCenter

=back

=head1 NETWORK_functions

=head2 NETWORK_add_function

=head3 SYNOPSIS

samu.pl network add [options]

=head3 OPTIONS

=over

=item ticket

Ticket to add network to

=item type

Type of network to add

=back

=head2 NETWORK_list_switch_function

=head3 SYNOPSIS

samu.pl network list_switch [options]

=head3 OPTIONS

=over

=back

=head2 NETWORK_list_dvp_function

=head3 SYNOPSIS

samu.pl network list_dvp [options]

=head3 OPTIONS

=over

=back

=head2 NETWORK_delete_function

=head3 SYNOPSIS

samu.pl network delete [options]

=head3 OPTIONS

=over

=item name

Name of device to delete

=item switch

Delete switch

=item dvp

Delete distributed Virtual Portgroup

=back

=head2 NETWORK_create_function

=head3 SYNOPSIS

samu.pl network create [options]

=head3 OPTIONS

=over

=item ticket

ticket to add interface to

=back
