=head1 Common_VI_options

=over

=item --config (variable VI_CONFIG)

Location of the VI Perl configuration file

=item --credstore (variable VI_CREDSTORE)

Name of the credential store file defaults to <HOME>/.vmware/credstore/vicredentials.xml on Linux and <APPDATA>/VMware/credstore/vicredentials.xml on Windows

=item --encoding (variable VI_ENCODING, default 'utf8')

Encoding: utf8, cp936 (Simplified Chinese), iso-8859-1 (German), shiftjis (Japanese)

=item --help or -h

Display usage information for the script

=item --passthroughauth (variable VI_PASSTHROUGHAUTH)

Attempt to use pass-through authentication

=item --passthroughauthpackage (variable VI_PASSTHROUGHAUTHPACKAGE, default 'Negotiate')

Pass-through authentication negotiation package

=item --password (variable VI_PASSWORD)

Password

=item --portnumber (variable VI_PORTNUMBER)

Port used to connect to server

=item --protocol (variable VI_PROTOCOL, default 'https')

Protocol used to connect to server

=item --savesessionfile (variable VI_SAVESESSIONFILE)

File to save session ID/cookie to utilize

=item --server (variable VI_SERVER, default 'localhost')

VI server to connect to. Required if url is not present

=item --servicepath (variable VI_SERVICEPATH, default '/sdk/webService')

Service path used to connect to server

=item --sessionfile (variable VI_SESSIONFILE)

File containing session ID/cookie to utilize

=item --url (variable VI_URL)

VI SDK URL to connect to. Required if server is not present

=item --username (variable VI_USERNAME)

User name

=item --verbose (variable VI_VERBOSE)

Display additional debugging information

=item --version

Display version information for the script

=back
