
=head1 NAME

samu.pl -- Support Automatisation Management Utility

=head1 DESCRIPTION

This script is used as a wrapper script for automatisation task used by support.
To get information about any sub module call any option with help. Documentation and information can be reached under the respective sub module help.

=head1 SYNOPSIS

samu.pl [options] [function]

=head1 OPTIONS

=over

=item --help|-h

Print the help page

=item --man|-m

Print the man page with information about all modules

=item -v|-vv|-vvv|-vvvv

Increase verbosity of printing

=item -q|-qq|-qqq|-qqqq|-qqqqq|-qqqqqq

Decrease verbosity of printing

=back

=head1 FUNCTIONS

=over

=item vm

Access VM Entity functions

=item datastore

Access Datastore functions

=item ticket

Access ticket functions

=item kayako

Access kayako functions

=item bugzilla

Access bugzilla functions

=item admin

Higher level commands for administering or maintenance of the VCenter and environment

=item network

Network related functions

=item devel

Developer functions

=back

=head1 VM

=head3 SYNOPSIS

samu.pl vm [options] [function]

=head3 OPTIONS

=over

=item --help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item clone

Sub used to provision virtual machine guests from templates.

=item add

Sub to add different hardware to a guest

=item list

Sub to list different hardware of a guest

=item delete

Sub to delete/remove different hardware of a guest

=item change

Sub to change settings of a guest

=item info

Sub used to dump information about a virtual machine

=item convert_full

Converts a linked clone to a full clone

=item run

Run a command in a guest that has vmware tools

=item customization_status

Prints the customization status

=item transfer

Transfers file from or to a guest

=back

=head1 VM_functions

=head2 VM_clone_function

=head3 SYNOPSIS

samu.pl vm clone [options]

=head3 OPTIONS

=over

=item ticket

The ticket attached to the environment

=item os_temp

Which template to use

=item parent_pool

The machine should not be created at standard pool

=item memory

The machine should have different amount of memory than template

=item cpu

The machine cpu count should be different than template

=item domain

By default machine is created in workgroup, this option changes it to be added to support domain (only win)

=back

=head2 VM_convert_full_function

=head3 SYNOPSIS

samu.pl vm convert_full [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=back

=head2 VM_info_function

=head3 SYNOPSIS

samu.pl vm info [options] [function]

=head3 OPTIONS

=over

=back

=head3 FUNCTIONS

=over

=item dumper

This information is used for development purposes, It dumps all object information about virtual machine to STDOUT

=item runtime

Information about runtime environment

=back

=head2 VM_info_dumper_function

=head3 SYNOPSIS

samu.pl vm info dumper [options]

=head3 OPTIONS

=over

=item vmname

Which machines information should we dump (dumps raw hash)

=back

=head2 VM_info_runtime_function

=head3 SYNOPSIS

samu.pl vm info runtime [options]

=head3 OPTIONS

=over

=item vmname

Which machines runtime information should we dump (dumps raw hash)

=back

=head2 VM_transfer_function

=head3 SYNOPSIS

samu.pl vm transfer [options]

=head3 OPTIONS

=over

=item type

Direction of transfer: to/from

=item vmname

Name of virtual machine

=item guestusername

Username to use for log on

=item guestpassword

Password to use to log on

=item source

Source of file

=item dest

Destination of file

=item overwrite

Should files be overwritten

=back

=head2 VM_run_function

=head3 SYNOPSIS

samu.pl vm run [options]

=head3 OPTIONS

=over

=item vmname

Which machines runtime information should we dump (dumps raw hash)

=item guestusername

Guestname to authenticate with

=item guestpassword

Password to authenticate with

=item prog

Program to run. Full path should be given

=item prog_arg

Arguments to program

=item workdir

Working directory

=item env

Enviromental variables passed to program

=back

=head2 VM_customization_status_function

=head3 SYNOPSIS

samu.pl vm customization_status [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item wait

Should we wait for Fail or Finished status

=back

=head2 VM_list_function

=head3 SYNOPSIS

samu.pl vm list [options] [function]

=head3 OPTIONS

=over

=back

=head3 FUNCTIONS

=over

=item interface

List networks interfaces attached to a virtual machine

=item cdrom

List cdroms attached to a virtual machine

=item disk

List disks attached to a virtual machine

=item snapshot

List snapshots attached to a virtual machine

=item process

List process or processes in guest with vmware tools installed

=item events

List events attached to a vm

=item templates

List provisioned templates

=back

=head2 VM_list_interface_function

=head3 SYNOPSIS

samu.pl vm list interface [options] [function]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item output

Output type: table or csv

=item noheader

should header informaiton be printed

=back

=head2 VM_list_cdrom_function

=head3 SYNOPSIS

samu.pl vm list cdrom [options] [function]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item output

Output type: table or csv

=item noheader

should header informaiton be printed

=back

=head2 VM_list_snapshot_function

=head3 SYNOPSIS

samu.pl vm list snapshot [options] [function]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item output

Type of output

=item noheader

Should header row be printed

=back

=head2 VM_list_disk_function

=head3 SYNOPSIS

samu.pl vm list disk [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item output

Output type: table or csv

=item noheader

should header informaiton be printed

=back

=head2 VM_list_process_function

=head3 SYNOPSIS

samu.pl vm list process [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item pid

Pid of requested program. Default is all programrams

=item guestusername

Username to authenticate with

=item guestpassword

Password to authenticate with

=item output

Output type: table or csv

=item noheader

should header informaiton be printed

=back

=head2 VM_list_events_function

=head3 SYNOPSIS

samu.pl vm list events [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item output

Output type: table or csv

=item noheader

Should header informtation be printed

=back

=head2 VM_list_templates_function

=head3 SYNOPSIS

samu.pl vm list templates [options]

=head3 OPTIONS

=over

=item output

Output type: table or csv

=item noheader

Should header informtation be printed

=back

=head2 VM_change_function

=head3 SYNOPSIS

samu.pl vm change [options] [function]

=head3 OPTIONS

=over

=back

=head3 FUNCTIONS

=over

=item cdrom

Change the backend iso to a cdrom drive

=item interface

Change the network connected to a network

=item altername

Change the alternative name of a virtual machine

=item snapshot

Revert to snapshot attached to a virtual machine

=item power

Change the power state of a virtual machine

=item disk

Change the size of hard disk

=back

=head2 VM_change_cdrom_function

=head3 SYNOPSIS

samu.pl vm change cdrom [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item num

Number of cdrom

=item iso

Datastore path to iso

=item unmount

Unmount the attached iso

=back

=head2 VM_change_interface_function

=head3 SYNOPSIS

samu.pl vm change interface [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item num

Number of interface

=item network

Name of network to change to

=back

=head2 VM_change_altername_function

=head3 SYNOPSIS

samu.pl vm change altername [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item name

New alternative virtual machine name

=back

=head2 VM_change_snapshot_function

=head3 SYNOPSIS

samu.pl vm change snapshot [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item id

ID of snapshot

=back

=head2 VM_change_power_function

=head3 SYNOPSIS

samu.pl vm change power [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item state

Power state on/off

=back

=head2 VM_change_disk_function

=head3 SYNOPSIS

samu.pl vm change disk [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item num

Number of hard disk

=item size

Requested new size

=back

=head2 VM_add_function

=head3 SYNOPSIS

samu.pl vm add [options] [function]

=head3 OPTIONS

=over

=back

=head3 FUNCTIONS

=over

=item cdrom

Add a cdrom drive to a virtual machine

=item interface

Add a network interface to a virtual machine

=item disk

Add a thin provisioned hard disk to a virtual machine

=item snapshot

Add snapshots to a virtual machine

=item folder

Create inventory folder on VCenter

=item resourcepool

Create resourcepool on VCenter

=back

=head2 VM_add_cdrom_function

=head3 SYNOPSIS

samu.pl vm add cdrom [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=back

=head2 VM_add_interface_function

=head3 SYNOPSIS

samu.pl vm add interface [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item type

Type of interface to add

=back

=head2 VM_add_disk_function

=head3 SYNOPSIS

samu.pl vm add disk [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item size

Requested size of disk

=back

=head2 VM_add_snapshot_function

=head3 SYNOPSIS

samu.pl vm add function [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item snap_name

Requested name of snapshot

=item desc

Snapshot description

=back

=head2 VM_add_folder_function

=head3 SYNOPSIS

samu.pl vm add folder [options]

=head3 OPTIONS

=over

=item name

Name of requested folder

=item parent

Name of requested parent. Defaults to virtual machine folder

=back

=head2 VM_add_resourcepool_function

=head3 SYNOPSIS

samu.pl vm add resourcepool [options]

=head3 OPTIONS

=over

=item name

Name of resourcepool

=item parent

Name of requested parent. Default to Resources folder

=back

=head2 VM_delete_function

=head3 SYNOPSIS

samu.pl vm delete [options] [function]

=head3 OPTIONS

=over

=back

=head3 FUNCTIONS

=over

=item hw

Delete the requested hardware

=item snapshot

Delete a snapshot attached to a virtual machine

=item entity

Delete a VMware entity

=back

=head2 VM_delete_hw_function

=head3 SYNOPSIS

samu.pl vm delete hw [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item id

ID of cdrom to delete

=item hw

Name of hw to delete. Cane be disk/cdrom/interface

=back

=head2 VM_delete_snapshot_function

=head3 SYNOPSIS

samu.pl vm delete snapshot [options]

=head3 OPTIONS

=over

=item vmname

Name of virtual machine

=item id

ID of snapshot to delete

=item all

Delete all snapshots

=back

=head2 VM_delete_entity_function

=head3 SYNOPSIS

samu.pl vm delete entity [options]

=head3 OPTIONS

=over

=item name

Name of Vmware entity

=item type

Type of entity to delete: VirtualMachine/ResourcePool/Folder

=back

=head1 TICKET

=head3 SYNOPSIS

samu.pl ticket [options] [function]


=head3 OPTIONS

=over

=item --help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item list

List all ticket on the ESXi, their owner, the kayako status currently, and if possible the Bugzilla status

=item info

List all machines attached to a ticket, and their login information

=item on

Turn all machines on attached to a ticket

=item off

Turn all machines off attached to a ticket

=item delete

Delete all entities attached to a ticket

=back

=head1 TICKET_functions

=head2 TICKET_list_function

=head3 SYNOPSIS

samu.pl ticket list [options]

=head3 OPTIONS

=over

=item output

Type of output

=item noheader

Should header row be printed

=back

=head2 TICKET_info_function

=head3 SYNOPSIS

samu.pl ticket info [options]

=head3 OPTIONS

=over

=item ticket

Ticket to gather information about

=back

=head2 TICKET_on_function

=head3 SYNOPSIS

samu.pl ticket on [options]

=head3 OPTIONS

=over

=item ticket

Power all machines on from ticket

=back

=head2 TICKET_off_function

=head3 SYNOPSIS

samu.pl ticket off [options]

=head3 OPTIONS

=over

=item ticket

Power all machines off from ticket

=back

=head2 TICKET_delete_function

=head3 SYNOPSIS

samu.pl ticket delete [options]

=head3 OPTIONS

=over

=item ticket

Delete all machines from ticket

=back

=head1 DATASTORE

=head3 SYNOPSIS

samu.pl datastore [options] [function]

=head3 OPTIONS

=over

=back

=head3 FUNCTIONS

=over

=item list

List datastores mounted on VCenter

=item add

Add a datastore to the VCenter

=item delete

Unmount and delete a datastore from the VCenter

=item info

Information about a datastore

=back

=head1 DATASTORE_functions

=head2 DATASTORE_list_function

=head3 SYNOPSIS

samu.pl datastore list [options]

=head3 OPTIONS

=over

=back

=head2 DATASTORE_add_function

=head3 SYNOPSIS

samu.pl datastore add [options]

=head3 OPTIONS

=over

=item datastore

Datastore name to add

=back

=head2 DATASTORE_delete_function

=head3 SYNOPSIS

samu.pl datastore delete [options]

=head3 OPTIONS

=over

=item datastore

Datastore name to delete

=back

=head2 DATASTORE_info_function

=head3 SYNOPSIS

samu.pl datastore info [options]

=head3 OPTIONS

=over

=item datastore

Datastore name to gather info about

=back

=head1 KAYAKO

=head3 SYNOPSIS

samu.pl kayako [options] [functions]

=head3 OPTIONS

=over

=item -help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item info

Gather information about ticket

=back

=head1 KAYAKO_functions

=head2 KAYAKO_info_function

=head3 SYNOPSIS

samu.pl kayako [options]

=head3 OPTIONS

=over

=item ticket

Number of ticket to get information

=back

=head1 BUGZILLA

=head3 SYNOPSIS

samu.pl bugzilla [options] [functions]

=head3 OPTIONS

=over

=item -help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item info

Gather information about bugzilla ticket

=back

=head1 BUGZILLA_functions

=head2 BUGZILLA_info_function

=head3 SYNOPSIS

samu.pl bugzilla [options]

=head3 OPTIONS

=over

=item ticket

The ticket number to gather information about

=back

=head1 ADMIN

=head3 SYNOPSIS

samu.pl admin [functions] [options]

=head3 OPTIONS

=over

=item --help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item cleanup

Start the cleanup task to remove empty entities on the VCenter

=item test

Test connection to VCenter. Prints the Server time

=item pod2wiki

Transfer a pod file to Dokuwiki format

=item list

List information about environment

=back

=head1 ADMIN_functions

=head2 ADMIN_cleanup_function

=head3 SYNOPSIS

samu.pl admin cleanup [options]

=head3 OPTIONS

=over

=back

=head2 ADMIN_test_function

=head3 SYNOPSIS

samu.pl admin test [options]

=head3 OPTIONS

=over

=back

=head2 ADMIN_pod2wiki_function

=head3 SYNOPSIS

samu.pl admin pod2wiki [options]

=head3 OPTIONS

=over

=item in

The POD file to transfer

=item out

The output file

=item page

Pagename to upload to with namespace example a/b/c
a/b is namespace
c is pagename

=item dokuuser

The username to log into dokuwiki

=item dokuserver

The Dokuwiki server to use to log into. Defaults to Support server

=item dokupass

The password to use to log into dokuwiki

=back

=head2 ADMIN_list_function

=head3 SYNOPSIS

samu.pl admin list [options] [functions]

=head3 OPTIONS

=over

=back

=head3 FUNCTIONS

=over

=item folder

List information about requested folders

=item resourcepool

list information about requested resourcepools

=item linked_clones

list all linked clones to a template

=item vms

list requested vms on vcenter

=back

=head2 ADMIN_list_folder_function

=head3 SYNOPSIS

samu.pl admin list folder [options]

=head3 OPTIONS

=over

=item all

List content of all folders

=item name

List content of one folder

=item output

Type of output

=item noheader

Header row should be printed

=back

=head2 ADMIN_list_resourcepool_function

=head3 SYNOPSIS

samu.pl admin list resourcepool [options]

=head3 OPTIONS

=over

=item user

List resourcepool information of user

=item all

List all resourcepool information

=item name

List information of only one requested resourcepool

=item output

Type of output

=item noheader

Header information should be printed

=back

=head2 ADMIN_list_linked_clones_function

=head3 SYNOPSIS

samu.pl admin list linked_clones [options]

=head3 OPTIONS

=over

=item template

Name of template to list linked clones of

=back

=head2 ADMIN_list_vms_function

=head3 SYNOPSIS

samu.pl admin list vms [options]

=head3 OPTIONS

=over

=item name

List specific user vms (default to username option)

=item vm

List specific vm attributes

=item all

List all vms on vcenter

=item output

Type of output

=item noheader

Header information should be printed

=back

=head1 NETWORK

Network related functions

=head3 SYNOPSIS

samu.pl network [options] [functions]

=head3 OPTIONS

=over

=item -help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item add

Add a distributed virtual switch to VCenter

=item create

Create a network interface with virtual machines

=item list_switch

List switches on VCenter

=item list_dvp

List distributed virtual portgroups on VCenter

=item delete

Remove distributed virtual switch from VCenter

=back

=head1 NETWORK_functions

=head2 NETWORK_add_function

=head3 SYNOPSIS

samu.pl network add [options]

=head3 OPTIONS

=over

=item ticket

Ticket to add network to

=item type

Type of network to add

=back

=head2 NETWORK_list_switch_function

=head3 SYNOPSIS

samu.pl network list_switch [options]

=head3 OPTIONS

=over

=back

=head2 NETWORK_list_dvp_function

=head3 SYNOPSIS

samu.pl network list_dvp [options]

=head3 OPTIONS

=over

=back

=head2 NETWORK_delete_function

=head3 SYNOPSIS

samu.pl network delete [options]

=head3 OPTIONS

=over

=item name

Name of device to delete

=item switch

Delete switch

=item dvp

Delete distributed Virtual Portgroup

=back

=head2 NETWORK_create_function

=head3 SYNOPSIS

samu.pl network create [options]

=head3 OPTIONS

=over

=item type

Type of interface to create

=item ticket

ticket to add interface to

=item vms

A comma separated list of vms to add to interface

=back

=head1 DEVEL

Devel related functions

=head3 SYNOPSIS

samu.pl devel [options] [functions]

=head3 OPTIONS

=over

=item -help|-h

Print the help page

=back

=head3 FUNCTIONS

=over

=item create

Create functions for developer

=back

=head1 DEVEL_functions

=head2 DEVEL_create_function

=head3 SYNOPSIS

samu.pl devel create [options]

=head3 OPTIONS

=over

=item mainpod

Creates a main pod from multiple files

=back

=head2 DEVEL_create_mainpod_function

=head3 SYNOPSIS

samu.pl create mainpod [options]

=head3 OPTIONS

=over

=item folder

Folder to take pod files from

=item output

Output file

=back

=head1 Common_VI_options

=over

=item --config (variable VI_CONFIG)

Location of the VI Perl configuration file

=item --credstore (variable VI_CREDSTORE)

Name of the credential store file defaults to <HOME>/.vmware/credstore/vicredentials.xml on Linux and <APPDATA>/VMware/credstore/vicredentials.xml on Windows

=item --encoding (variable VI_ENCODING, default 'utf8')

Encoding: utf8, cp936 (Simplified Chinese), iso-8859-1 (German), shiftjis (Japanese)

=item --help or -h

Display usage information for the script

=item --passthroughauth (variable VI_PASSTHROUGHAUTH)

Attempt to use pass-through authentication

=item --passthroughauthpackage (variable VI_PASSTHROUGHAUTHPACKAGE, default 'Negotiate')

Pass-through authentication negotiation package

=item --password (variable VI_PASSWORD)

Password

=item --portnumber (variable VI_PORTNUMBER)

Port used to connect to server

=item --protocol (variable VI_PROTOCOL, default 'https')

Protocol used to connect to server

=item --savesessionfile (variable VI_SAVESESSIONFILE)

File to save session ID/cookie to utilize

=item --server (variable VI_SERVER, default 'localhost')

VI server to connect to. Required if url is not present

=item --servicepath (variable VI_SERVICEPATH, default '/sdk/webService')

Service path used to connect to server

=item --sessionfile (variable VI_SESSIONFILE)

File containing session ID/cookie to utilize

=item --url (variable VI_URL)

VI SDK URL to connect to. Required if server is not present

=item --username (variable VI_USERNAME)

User name

=item --verbose (variable VI_VERBOSE)

Display additional debugging information

=item --version

Display version information for the script

=back

=head1 FILES

SDK uses the default ~/.visdkrc for storing environmental values.
Further information can be found on: https://supportwiki.balabit/doku.php/products:vmware:infra_info
The file should have following content:

    VI_USERNAME=
    VI_PASSWORD=
    VI_SERVER=10.21.0.1
    VI_URL=https://10.21.0.1/sdk
    VI_PORTNUMBER=443
    VI_PROTOCOL=HTTPS
    VI_SERVICEPATH=/sdk/webService

You only need to fill the user name and password entry with your AD user name/password
In .bashrc the following entry should also be added:

    PERL_LWP_SSL_VERIFY_HOSTNAME=0

=head1 INSTALLATION

To test all required modules with required versions two scripts are required.

=head2 dependency

Two deb files have been created to make dependency install easier. they can be found under the deb folder.

=over

=item balabit-prereq

These packages are needed to run the normal scripts

=item balabit-test-prereq

These packages are needed to run the test scripts. Some packages can only be installed from CPAN, README should contain additional information

=back

To install the dependencies please do following:

    dpkg -i deb/<package>.deb
    apt-get install -f

=head2 generate_perl_modules.sh+TEST_PERL_MODULES.pl

=over

=item generate_perl_modules.sh

This script will help to generate a list of modules from scripts that are up to date. Under normal circumstances you don't need to run this script
This script will generate the PERL_MODULES file which is required by TEST_PERL_MODULES.pl

=item TEST_PERL_MODULES.pl

This script will do a test require on all modules in PERL_MODULES, and test if they can be loaded successfully
If you would like to test if the modules for running the test framework are installed run it with environment variable TEST

    TEST=1 ./TEST_PERL_MODULES.pl

=back

=head2 Makefile.PL

This is the official version from CPAN how to distribute and test modules. Makefile.PL contains all modules needed to run or test the code/modules.
To run it do:

    perl Makefile.PL

It will print information if any module is missing any required version of a module.
To clean up files generated by the Makefile.PL run following commands:

    make clean
    rm Makefile.old

=head3 Tests

To run tests either make or prove can be used.

=over

=item prove

Prove is installed with Test::More and is a command line interface to run tests:

    prove -l t/*

=item Makefile.PL

Makefile.PL can be used to run the test suite with make:

    perl Makefile.PL
    make test
    make clean
    rm Makefile.old

=back

=head3 test_variables

Some tests are skipped because normal environment they shouldn't be run or used. If required to be run the following environment variables need to be configured:

=over

=item DNS

This will run DNS queries to see if resolve is working

=item AUTHOR

This will check if AUTHOR has not forgotten to update specific tests, or left fix me -s in the code

=item CRITIC

This will criticise the code to see if it is tidy, or perl standards have been used

=item POD

This will run tests on the pod file

=item ALL

This will run all above tests

=back

=head1 LOGLEVEL

In the framework we use 10 levels for logs. Default is 6

=over

=item 10 DEBUG2

Very Verbose information, mostly variables and objects are dumped at this level

=item 9  DEBUG1

Variables are dumped at this level

=item 8  DEBUG

Subroutine entries and exists are logged

=item 7  INFO

Information messages printed

=item 6  NOTICE

Notice messages are printed. This is default level

=item 5  WARNING

Warning messages are printed

=item 4  ERROR

Errors are printed

=item 3  CRITICAL

Critical messages are printed

=item 2  ALERT

Alert messages are printed

=item 1  EMERGENCY

Emergency messages are printed

=item 0

At this level no information is printed. This level should very rarely be used

=back

=head1 BUGS

Known Bugs:

=over

=item * There is a lot of anal sex happening at my desk

=back

=head1 AUTHOR

Krisztian Banhidy <s4mur4i@balabit.hu>

=head1 LOGO

                            /|
                          /'||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||
                         |  ||         __.--._
                         |  ||      /~~   __.-~\ _
                         |  ||  _.-~ / _---._ ~-\/~\
                         |  || // /  /~/  .-  \  /~-\
                         |  ||((( /(/_(.-(-~~~~~-)_/ |
                         |  || ) (( |_.----~~~~~-._\ /
                         |  ||    ) |              \_|
                         |  ||     (| =-_   _.-=-  |~)        ,
                         |  ||      | `~~ |   ~~'  |/~-._-'/'/_,
                         |  ||       \    |        /~-.__---~ , ,
                         |  ||       |   ~-''     || `\_~~~----~
                         |  ||_.ssSS$$\ -====-   / )\_  ~~--~
                 ___.----|~~~|%$$$$$$/ \_    _.-~ /' )$s._
        __---~-~~        |   |%%$$$$/ /  ~~~~   /'  /$$$$$$$s__
      /~       ~\    ============$$/ /        /'  /$$$$$$$$$$$SS-.
    /'      ./\\\\\\_( ~---._(_))$/ /       /'  /$$$$%$$$$$~      \
    (      //////////(~-(..___)/$/ /      /'  /$$%$$%$$$$'         \
     \    |||||||||||(~-(..___)$/ /  /  /'  /$$$%$$$%$$$            |
      `-__ \\\\\\\\\\\(-.(_____) /  / /'  /$$$$%$$$$$%$             |
          ~~""""""""""-\.(____) /   /'  /$$$$$%%$$$$$$\_            /
                        $|===|||  /'  /$$$$$$$%%%$$$$$( ~         ,'|
                    __  $|===|%\/'  /$$$$SAMU$$$%%%%$$|        ,''  |
                   ///\ $|===|/'  /$$$$$$%$$$$$$$%%%%$(            /'
                    \///\|===|  /$$$$$$$$$%%$$$$$$%%%%$\_-._       |
                     `\//|===| /$$$$$$$$$$$%%%$$$$$$-~~~    ~      /
                       `\|-~~(~~-`$$$$$$$$$%%%///////._       ._  |
                       (__--~(     ~\\\\\\\\\\\\\\\\\\\\        \ \
                       (__--~~(       \\\\\\\\\\\\\\\\\\|        \/
                        (__--~(       ||||||||||||||||||/       _/
                         (__.--._____//////////////////__..---~~
                         |   """"'''''           ___,,,,ss$$$%
                        ,%\__      __,,,\sssSS$$$$$$$$$$$$$$%%
                      ,%%%%$$$$$$$$$$\;;;;\$$$$$$$$$$$$$$$$%%%$.
                     ,%%%%%%$$$$$$$$$$%\;;;;\$$$$$$$$$$$$%%%$$$$
                   ,%%%%%%%%$$$$$$$$$%$$$\;;;;\$$$$$$$$$%%$$$$$$,
                  ,%%%%%%%%%$$$$$$$$%$$$$$$\;;;;\$$$$$$%%$$$$$$$$
                 ,%%%%%%%%%%%$$$$$$%$Support\;;;;\$$$%$$$$$$$$$$$
                 %%%%%%%%%%%%$#Automatisation$\;;;$$$$$$$$$$$$$$$
                   ""==%%%%%%%$$Management###$$$$$$$$$$$$$$$$$SV"
                               $$Util$$$$$$$$$$$$$$====""""
                                 """"""""~~~~


=cut
